source 'https://rubygems.org'

gem 'roda'
gem 'roda-opal_assets'
gem 'puma'
gem 'rake'

group :development do
  gem 'rerun'

  # Assets from these gems won't be needed in production since they'll be
  # precompiled
  gem 'clearwater', '~> 1.0.0.rc4'
  gem 'grand_central', '~> 0.6.0'
  gem 'grand_central-dev_tools'
  gem 'clearwater-hot_loader'
end
