require 'bundler'
Bundler.setup :default, ENV.fetch('RACK_ENV') { :development }
$LOAD_PATH << 'app'

require 'opal'
require 'clearwater'
require 'roda/opal_assets'
require 'assets'

# Keep a single asset compiler in case we want to use it for multiple tasks.
assets = Roda::OpalAssets.new(env: :production)

desc 'Precompile assets for production'
task 'assets:precompile' do
  warn = method(:warn)
  module Kernel
    def warn(*)
    end
  end
  assets << 'app.js'
  assets.build

  Kernel.class_exec do
    define_method :warn, &warn
  end
end
